### ISSUE TITLE
Correcciones entrega 2

### ISSUE THREAD

**Issue by briangraj** [nicolaslazo/trabajos-paradigmas#4]
- deReversa: puede usar directamente cambiarNaftaSegun

- en varios partes hacen "cambiarParticipantesSegun (map ...)", deleguenlo

- esNaftaMenorA: es innecesaria

- calcularCombustibleVuelta: se complicaron mucho para hacer la cuenta, directamente puede ser: -(velocidad unAuto / 10 * longitudPista unaCarrera)

- loVenSusEnamorades y correrCarrera: en el otherwise no es necesario id

- correrCarrera: no es la idea que la carrera quede con 0 vueltas luego de finalizar. Piensen otra forma de hacerlo sin modificar las vueltas de la carrera

- elGranTruco: este tipo de recursividad ya es resuelta por foldl, usenlo

**Comment by nicolaslazo** [comment]
Para el que quiera terminar la corrección, falta arreglar elGranTruco y la delegación del segundo item
