### ISSUE TITLE
Correcciones lógico

### ISSUE THREAD

**Issue by briangraj** [nicolaslazo/trabajos-paradigmas#5]
- sePostulanEn: la relación es entre una provincia y un partido, pongan el nombre en singular

- leGanaA: en vez de CandidatoA y CandidatoB usen CandidatoGanador y CandidatoPerdedor (también cambien el nombre de otras variables con estos nombres). En la segunda regla deleguen que no sean del mismo partido y que el ganador tenga mayor porcentaje en otros 2 predicados

- falta responder las preguntas del punto 4

- ganabaEnProvincia: se complicaron mucho para saber el ganador, en el forall pueden directamente comparar las intenciones de voto (que es lo que terminan haciendo en leGanaPorIntencionDeVotosA/3)

- ajusteConsultora: están repitiendo lógica. Lo que cambia entre reglas es la cantidad a ajustar, que depende de si el partido ganaba o no, traten de delegar eso

- influenciaDePromesas: no es inversible (falta generar la promesa). En la ultima regla cuál es la intención del forall? Además el 1er parámetro tendría que matchear por el functor construir

- porcentajeDeEdilicio: para no repetir el nombre del functor pasen como parámetros el tipo y la cantidad directamente. Las 2 reglas de comisaria tienen que ser excluyentes entre sí, aunque la segunda sume 0

- promedioDeCrecimiento: no es inversible (falta generar el partido). Si bien el predicado se llama promedio, no pide hacer un promedio (le pusimos un mal nombre) sino la sumatoria de los porcentajes

**Comment by nicolaslazo** [comment]
1. sePostulanEn: hecho

2. leGanaA: hecho

3. falta responder las preguntas del punto 4

4. ganabaEnProvincia: hecho

5. ajusteConsultora: la cantidad de líneas es la misma, no estoy seguro de si hice eso bien

6. influenciaDePromesas: no supe hacerlo

7. porcentajeDeEdilicio: no supe hacerlo

8. promedioDeCrecimiento: hecho

**Comment by briangraj** [comment]
Me acabo de dar cuenta que el punto 5 también tiene preguntas, así que falta eso también.

ajusteConsultora está bien. Acá no es importante la cantidad de lineas sino evitar la repetición de lógica.

**Comment by briangraj** [comment]
influenciaDePromesas: para que sea inversible hay que generar la promesa, para eso la promesa tiene que ser una variable, entonces les quedaría: influenciaDePromesas(Promesa, Variacion). Ahora se puede generar Promesa con promete/2 y una vez ligada la promesa, relacionarla con su Variacion (que es lo que hacen los predicados que tienen ahora). En la última regla de influenciaDePromesas, Edilicios lo toman como lista pero es una functor así que debería ser: influenciaDePromesas(construir(Edilicios), VariacionTotal)

porcentajeDeEdilicio: la idea es que los predicados queden de la forma:
porcentajeDeEdilicio(jardin, N, Porcentaje) :-
	Porcentaje is (0.1) * N.

Entonces en vez de hacer pattern matching en porcentajeDeEdilicio lo hacen en donde se llame al predicado, en este caso sería en el segundo argumento del findall en influenciaDePromesas. Entonces en vez de ligar Edilicio tiene que ligar Tipo y Cantidad usando el functor: edilicio(Tipo, Cantidad)

**Comment by delficostanzo** [comment]
Ya corregi porcentajeDeEdilicio! Esta bien como pase el functor en el segundo argumento del findall en influenciaDePromesas?

**Comment by briangraj** [comment]
Casi. Primero fíjate que a porcentajeDeEdilicio le estás pasando 2 parámetros pero ahora recibe 3 parámetros, entonces Tipo y Cantidad tienen que ser 
2 parámetros separados, y no parte de un functor. Pero para poder hacer esto primero tenés ligarlos. Además en la línea 238 estás ligando Edilicio, que es el functor, y no se usa en otra parte. Entonces en vez de ligar el functor con Edilicio tenés que ligar Tipo y Cantidad usando el functor.

**Comment by delficostanzo** [comment]
Ahh okei entendi, pero Tipo y Cantidad se tendrian que ligar arriba de todo? Porque no entendi lo que dijiste de la linea 238.

**Comment by briangraj** [comment]
En la línea 238 en vez de hacer member(Edilicio,...) hacé member(edilicio(Tipo, Cantidad), ...)

**Comment by delficostanzo** [comment]
Ahh perfecto, ahi lo modifique

**Comment by briangraj** [comment]
Estuve viendo lo que hicieron y está todo bien, cierro el issue.
